apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        data-platform-skn/jx3-golang-1: true
        data-platform-skn/jx3-minikube-1: true
        data-platform-skn/jx3-sb: true
        data-platform-skn/jx3-springboot: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        data-platform-skn/jx3-golang-1: merge
        data-platform-skn/jx3-minikube-1: merge
        data-platform-skn/jx3-sb: merge
        data-platform-skn/jx3-springboot: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - data-platform-skn/jx3-minikube-1
        - data-platform-skn/jx3-golang-1
        - data-platform-skn/jx3-sb
        - data-platform-skn/jx3-springboot
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - data-platform-skn/jx3-minikube-1
        - data-platform-skn/jx3-golang-1
        - data-platform-skn/jx3-sb
        - data-platform-skn/jx3-springboot
      target_url: http://dashboard-jx.192.168.64.7.nip.io
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
